/**
 * pdf-reports.js — PDF report generation for P&L statements and tax summaries
 * Uses jsPDF (loaded lazily from CDN) for client-side PDF generation.
 */

import { inv, sales, expenses, getInvItem } from '../data/store.js';
import { fmt, pct, ds } from '../utils/format.js';
import { getPlatforms } from '../features/platforms.js';
import { toast } from '../utils/dom.js';

let _jsPDF = null;

async function loadJsPDF() {
  if (_jsPDF) return _jsPDF;
  // Dynamically load jsPDF from CDN
  return new Promise((resolve, reject) => {
    if (window.jspdf) { _jsPDF = window.jspdf; resolve(_jsPDF); return; }
    const script = document.createElement('script');
    script.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.2/jspdf.umd.min.js';
    script.onload = () => { _jsPDF = window.jspdf; resolve(_jsPDF); };
    script.onerror = () => reject(new Error('Failed to load jsPDF'));
    document.head.appendChild(script);
  });
}

// ── Helper: Add FlipTrack header to PDF ──────────────────────────────────
function addHeader(doc, title, subtitle) {
  doc.setFillColor(10, 10, 15);
  doc.rect(0, 0, 210, 30, 'F');
  doc.setTextColor(0, 200, 136);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('FlipTrack', 14, 16);
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(title, 65, 14);
  doc.setFontSize(8);
  doc.setTextColor(160, 160, 180);
  doc.text(subtitle, 65, 20);
  doc.setTextColor(0, 0, 0);
  return 38; // starting Y position after header
}

function addFooter(doc, pageNum) {
  const h = doc.internal.pageSize.getHeight();
  doc.setFontSize(7);
  doc.setTextColor(140, 140, 160);
  doc.text(`Generated by FlipTrack · ${new Date().toLocaleDateString()}`, 14, h - 8);
  doc.text(`Page ${pageNum}`, 196, h - 8, { align: 'right' });
}

// ── P&L STATEMENT ────────────────────────────────────────────────────────
export async function exportPLReport(dateFrom, dateTo) {
  toast('Generating P&L report…');
  const { jsPDF } = await loadJsPDF();
  const doc = new jsPDF();

  const from = dateFrom ? new Date(dateFrom) : new Date(new Date().getFullYear(), 0, 1);
  const to = dateTo ? new Date(dateTo) : new Date();
  const label = `${from.toLocaleDateString()} — ${to.toLocaleDateString()}`;

  let y = addHeader(doc, 'Profit & Loss Statement', label);

  // Calculate P&L
  let totalRev = 0, totalCOGS = 0, totalFees = 0, totalShip = 0;
  const periodSales = sales.filter(s => {
    const d = new Date(s.date);
    return d >= from && d <= to;
  });

  for (const s of periodSales) {
    const it = getInvItem(s.itemId);
    totalRev += (s.price || 0) * (s.qty || 0);
    totalCOGS += it ? (it.cost || 0) * (s.qty || 0) : 0;
    totalFees += s.fees || 0;
    totalShip += s.ship || 0;
  }

  const periodExpenses = expenses.filter(e => {
    const d = new Date(e.date);
    return d >= from && d <= to;
  });
  const totalExp = periodExpenses.reduce((a, e) => a + (e.amount || 0), 0);
  const grossProfit = totalRev - totalCOGS;
  const netProfit = grossProfit - totalFees - totalShip - totalExp;

  // Revenue Section
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Revenue', 14, y);
  y += 8;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Sales Revenue (${periodSales.length} transactions)`, 20, y);
  doc.text(fmt(totalRev), 196, y, { align: 'right' });
  y += 12;

  // COGS
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Cost of Goods Sold', 14, y);
  y += 8;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Product Cost (COGS)', 20, y);
  doc.text(`(${fmt(totalCOGS)})`, 196, y, { align: 'right' });
  y += 6;
  doc.text('Platform Fees', 20, y);
  doc.text(`(${fmt(totalFees)})`, 196, y, { align: 'right' });
  y += 6;
  doc.text('Shipping Costs', 20, y);
  doc.text(`(${fmt(totalShip)})`, 196, y, { align: 'right' });
  y += 10;

  // Gross Profit
  doc.setDrawColor(0, 200, 136);
  doc.line(14, y, 196, y);
  y += 6;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Gross Profit', 14, y);
  doc.setTextColor(grossProfit >= 0 ? 0 : 200, grossProfit >= 0 ? 150 : 50, grossProfit >= 0 ? 100 : 50);
  doc.text(fmt(grossProfit), 196, y, { align: 'right' });
  doc.setTextColor(0, 0, 0);
  y += 12;

  // Operating Expenses
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Operating Expenses', 14, y);
  y += 8;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  // Group expenses by category
  const expByCat = {};
  for (const e of periodExpenses) {
    const cat = e.category || 'Other';
    expByCat[cat] = (expByCat[cat] || 0) + (e.amount || 0);
  }
  for (const [cat, amt] of Object.entries(expByCat).sort((a, b) => b[1] - a[1])) {
    doc.text(cat, 20, y);
    doc.text(`(${fmt(amt)})`, 196, y, { align: 'right' });
    y += 6;
  }
  if (!periodExpenses.length) {
    doc.text('No operating expenses recorded', 20, y);
    y += 6;
  }
  y += 6;

  // Net Profit
  doc.setDrawColor(0, 200, 136);
  doc.setLineWidth(0.5);
  doc.line(14, y, 196, y);
  y += 2;
  doc.line(14, y, 196, y);
  y += 8;
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Net Profit', 14, y);
  doc.setTextColor(netProfit >= 0 ? 0 : 200, netProfit >= 0 ? 150 : 50, netProfit >= 0 ? 100 : 50);
  doc.text(fmt(netProfit), 196, y, { align: 'right' });
  doc.setTextColor(0, 0, 0);
  y += 8;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const margin = totalRev ? netProfit / totalRev : 0;
  doc.text(`Net Margin: ${pct(margin)} · ROI: ${totalCOGS ? pct(netProfit / totalCOGS) : 'N/A'}`, 14, y);

  addFooter(doc, 1);

  // Platform Breakdown Page
  if (periodSales.length) {
    doc.addPage();
    let y2 = addHeader(doc, 'Revenue by Platform', label);

    const platRev = {};
    for (const s of periodSales) {
      const it = getInvItem(s.itemId);
      const plats = it ? getPlatforms(it) : ['Other'];
      const rev = (s.price || 0) * (s.qty || 0);
      plats.forEach(p => { platRev[p] = (platRev[p] || 0) + rev / plats.length; });
    }

    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Platform', 20, y2);
    doc.text('Revenue', 120, y2);
    doc.text('% of Total', 160, y2, { align: 'right' });
    doc.text('Sales', 196, y2, { align: 'right' });
    y2 += 4;
    doc.setDrawColor(200, 200, 200);
    doc.line(20, y2, 196, y2);
    y2 += 6;

    doc.setFont('helvetica', 'normal');
    const total = Object.values(platRev).reduce((a, v) => a + v, 0);
    for (const [plat, rev] of Object.entries(platRev).sort((a, b) => b[1] - a[1])) {
      const platSales = periodSales.filter(s => {
        const it = getInvItem(s.itemId);
        return it && getPlatforms(it).includes(plat);
      }).length;
      doc.text(plat, 20, y2);
      doc.text(fmt(rev), 120, y2);
      doc.text(pct(rev / total), 160, y2, { align: 'right' });
      doc.text(String(platSales), 196, y2, { align: 'right' });
      y2 += 7;
    }

    addFooter(doc, 2);
  }

  doc.save(`FlipTrack_PL_${from.toISOString().slice(0, 10)}_${to.toISOString().slice(0, 10)}.pdf`);
  toast('P&L report downloaded ✓');
}

// ── TAX SUMMARY REPORT ──────────────────────────────────────────────────
export async function exportTaxReport(year) {
  toast('Generating tax summary…');
  const { jsPDF } = await loadJsPDF();
  const doc = new jsPDF();
  const yr = year || new Date().getFullYear();

  let y = addHeader(doc, 'Tax Summary Report', `Fiscal Year ${yr}`);

  const from = new Date(yr, 0, 1);
  const to = new Date(yr, 11, 31, 23, 59, 59);

  let totalRev = 0, totalCOGS = 0, totalFees = 0, totalShip = 0, unitsSold = 0;
  const yearSales = sales.filter(s => {
    const d = new Date(s.date);
    return d >= from && d <= to;
  });

  for (const s of yearSales) {
    const it = getInvItem(s.itemId);
    totalRev += (s.price || 0) * (s.qty || 0);
    totalCOGS += it ? (it.cost || 0) * (s.qty || 0) : 0;
    totalFees += s.fees || 0;
    totalShip += s.ship || 0;
    unitsSold += s.qty || 0;
  }

  const yearExp = expenses.filter(e => {
    const d = new Date(e.date);
    return d >= from && d <= to;
  });
  const totalExp = yearExp.reduce((a, e) => a + (e.amount || 0), 0);

  // Income section
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('INCOME', 14, y);
  y += 8;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Gross Sales Revenue`, 20, y);
  doc.text(fmt(totalRev), 196, y, { align: 'right' });
  y += 6;
  doc.text(`Total Transactions: ${yearSales.length} · Units Sold: ${unitsSold}`, 20, y);
  y += 12;

  // Deductions
  doc.setFont('helvetica', 'bold');
  doc.text('DEDUCTIONS (Schedule C)', 14, y);
  y += 8;
  doc.setFont('helvetica', 'normal');

  const deductions = [
    ['Cost of Goods Sold (COGS)', totalCOGS],
    ['Platform & Selling Fees', totalFees],
    ['Shipping & Postage', totalShip],
  ];

  // Add expense categories
  const expCats = {};
  for (const e of yearExp) {
    const cat = e.category || 'Other Business Expense';
    expCats[cat] = (expCats[cat] || 0) + (e.amount || 0);
  }
  for (const [cat, amt] of Object.entries(expCats).sort((a, b) => b[1] - a[1])) {
    deductions.push([cat, amt]);
  }

  const totalDeductions = totalCOGS + totalFees + totalShip + totalExp;
  for (const [label, amt] of deductions) {
    doc.text(label, 20, y);
    doc.text(fmt(amt), 196, y, { align: 'right' });
    y += 6;
  }
  y += 4;
  doc.setDrawColor(0, 200, 136);
  doc.line(14, y, 196, y);
  y += 6;
  doc.setFont('helvetica', 'bold');
  doc.text('Total Deductions', 20, y);
  doc.text(fmt(totalDeductions), 196, y, { align: 'right' });
  y += 12;

  // Net Income
  const netIncome = totalRev - totalDeductions;
  doc.setFontSize(13);
  doc.text('NET BUSINESS INCOME', 14, y);
  doc.setTextColor(netIncome >= 0 ? 0 : 200, netIncome >= 0 ? 150 : 50, netIncome >= 0 ? 100 : 50);
  doc.text(fmt(netIncome), 196, y, { align: 'right' });
  doc.setTextColor(0, 0, 0);
  y += 12;

  // Disclaimer
  doc.setFontSize(8);
  doc.setTextColor(140, 140, 140);
  doc.text('This report is for informational purposes only and does not constitute tax advice.', 14, y);
  y += 4;
  doc.text('Consult a qualified tax professional for filing. FlipTrack is not a CPA or tax preparation service.', 14, y);

  // Inventory valuation
  const endingInv = inv.reduce((a, i) => a + (i.cost || 0) * (i.qty || 0), 0);
  y += 12;
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('ENDING INVENTORY VALUATION', 14, y);
  y += 7;
  doc.setFont('helvetica', 'normal');
  doc.text(`${inv.filter(i => i.qty > 0).length} items in stock`, 20, y);
  doc.text(fmt(endingInv), 196, y, { align: 'right' });

  addFooter(doc, 1);
  doc.save(`FlipTrack_Tax_${yr}.pdf`);
  toast('Tax summary downloaded ✓');
}
